"""empty message

Revision ID: 014f3d7d603a
Revises: 385cea900e01
Create Date: 2023-11-10 00:31:47.639470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '014f3d7d603a'
down_revision = '385cea900e01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('text', sa.String(length=120), nullable=False))
        batch_op.drop_column('task')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.drop_column('text')
        batch_op.drop_column('date')

    # ### end Alembic commands ###
