"""empty message

Revision ID: 34918128421f
Revises: aac8f5bee0ca
Create Date: 2023-10-26 03:45:00.787684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34918128421f'
down_revision = 'aac8f5bee0ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('row',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('prueba')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prueba',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='prueba_pkey')
    )
    op.drop_table('row')
    # ### end Alembic commands ###
