"""empty message

Revision ID: 385cea900e01
Revises: b6d6318e9c94
Create Date: 2023-11-09 23:38:05.763727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '385cea900e01'
down_revision = 'b6d6318e9c94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task', sa.String(length=120), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task')
    # ### end Alembic commands ###
