"""empty message

Revision ID: 406dfbe79b74
Revises: 1dde091d527b
Create Date: 2023-11-09 15:46:45.488104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '406dfbe79b74'
down_revision = '1dde091d527b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invitation_client_form',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invitation_hash', sa.String(length=9999), nullable=False),
    sa.Column('expired_form', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invitation_client_form')
    # ### end Alembic commands ###
