"""empty message

Revision ID: 604f5f4cfdbf
Revises: 8b881f5a6fc0
Create Date: 2023-10-29 03:36:22.773723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '604f5f4cfdbf'
down_revision = '8b881f5a6fc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.alter_column('business',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=40),
               existing_nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=120),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
        batch_op.alter_column('business',
               existing_type=sa.String(length=40),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)

    # ### end Alembic commands ###
