"""empty message

Revision ID: b6d6318e9c94
Revises: 04ab38f66bd3
Create Date: 2023-11-08 17:28:30.002931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6d6318e9c94'
down_revision = '04ab38f66bd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_constraint('payment_date_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.create_unique_constraint('payment_date_key', ['date'])

    # ### end Alembic commands ###
